[package]
name = "libuv-sys2"
version = "1.35.3"
description = "Thin FFI bindings for libuv"
homepage = "https://github.com/bmatcuk/libuv-sys/"
repository = "https://github.com/bmatcuk/libuv-sys/"
categories = ["command-line-interface", "external-ffi-bindings"]
keywords = ["events", "libevent", "loop"]
readme = "README.md"
license-file = "LICENSE"
authors = ["Bob Matcuk <bmatcuk@gmail.com>"]
edition = "2018"
links = "uv"

[badges]
travis-ci = { repository = "bmatcuk/libuv-sys" }
maintenance = { status = "actively-developed" }

[build-dependencies]
bindgen = { version = "0.53.2", default-features = false, features = ["runtime"] }
cc = "1.0"
pkg-config = "0.3.17"

[target.'cfg(windows)'.build-dependencies]
nt_version = "0.1.3"
